---
engines:
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.coffee"
  - "**.js"
exclude_paths:
- spec/
- build/
